import boto3
import logging
from botocore.config import Config
import os
from dotenv import load_dotenv

load_dotenv()

aws_access_key_id = os.getenv("AWS_ACCESS_KEY_ID")
aws_secret_access_key = os.getenv("AWS_SECRET_ACCESS_KEY")

def get_s3_client():
    session = boto3.Session(
        aws_access_key_id=aws_access_key_id,
        aws_secret_access_key=aws_secret_access_key,
        region_name='us-east-1'
    )
    s3 = session.client('s3', config=Config(signature_version='s3v4'))
    return s3

# Upload wav and tsv files from video pipeline to s3
def write_file_to_s3(user_id, source_name):
    from pathlib import Path
    source = Path(source_name)
    base_dir = source.parent
    stem = source.stem
    folder_key = f"{user_id}/{stem}"

    s3_client = get_s3_client()
    for ext in [".tsv", ".wav"]:
        local_path = base_dir / f"{stem}{ext}"
        if not local_path.exists():
            logging.warning(f"[File Upload] Expected file not found: {local_path}")
            continue
        key_path = f"{folder_key}/{local_path.name}"
        try:
            s3_client.upload_file(str(local_path), 'neuro-bucket', key_path)
            logging.info(f"[File Upload] Uploaded {local_path} to s3://neuro-bucket/{key_path}")
            local_path.unlink()
            logging.info(f"[File Upload] Deleted local file: {local_path}")
        except Exception as e:
            logging.error(f"[File Upload] Error uploading file: {e}")
            raise ValueError(f"Error uploading file: {e}")

# Upload mp3 and tsv files from text pipeline to s3, then clean up temp dir
def upload_text_pipeline_files(user_id, source_name, tmpdir):
    import shutil
    from pathlib import Path
    stem = Path(source_name).stem
    folder_key = f"{user_id}/{stem}"
    cache_dir = Path("./cache")

    s3_client = get_s3_client()
    # Find .mp3 and .tsv files generated by TRIBE in the cache folder
    for f in cache_dir.rglob("*.mp3"):
        _upload_and_delete(s3_client, f, f"{folder_key}/{f.name}")
        tsv = f.with_suffix(".tsv")
        if tsv.exists():
            _upload_and_delete(s3_client, tsv, f"{folder_key}/{tsv.name}")
    # Clean up the temp input directory
    shutil.rmtree(tmpdir, ignore_errors=True)

def _upload_and_delete(s3_client, local_path, key_path):
    try:
        s3_client.upload_file(str(local_path), 'neuro-bucket', key_path)
        logging.info(f"[File Upload] Uploaded {local_path} to s3://neuro-bucket/{key_path}")
        local_path.unlink()
        logging.info(f"[File Upload] Deleted local file: {local_path}")
    except Exception as e:
        logging.error(f"[File Upload] Error uploading file: {e}")
        raise ValueError(f"Error uploading file: {e}")